project_id = "fidvjfsawgmdjtivlcpi"

[functions.get-stream-url]
verify_jwt = false

[functions.resolve-stream]
verify_jwt = false

[functions.resolve-txt-stream]
verify_jwt = false

[functions.tmdb-lookup]
verify_jwt = false

[functions.scrape-channels]
verify_jwt = false

[functions.bulk-update-tmdb]
verify_jwt = false

[functions.bulk-import-tmdb]
verify_jwt = false

[functions.generate-insight]
verify_jwt = false

[functions.xtream-search]
verify_jwt = false